### ISSUE TITLE
Trying to run with remote db

### ISSUE THREAD

**Issue by eamonpenland** [andrewtimberlake/migratrex#4]
```
(MatchError) no match of right hand side value: {:ok, #PID<0.181.0>, [:connection, :db_connection, :postgrex]}
    lib/mix/tasks/migratrex.ex:28: anonymous fn/2 in Mix.Tasks.Migratrex.run/1
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2

```

Hey! Im trying to use this with a remote db connection, but cannot seem to get this to work.

Tried pulling the latest pull request(updated with latest ecto) and running the mix migratrex with a phoenix app. The error above is what I get. Am I missing something?

 Thanks

**Comment by eamonpenland** [comment]
got it working with the updated ecto request
